### ISSUE TITLE
Installs okay, but createrepo won't run

### ISSUE THREAD

**Issue by ghost** [stepanstipl/homebrew-noop#3] opened 2015-04-15 01:03 UTC
I get the following error:

Traceback (most recent call last):
  File "/usr/local/share/createrepo/genpkgmetadata.py", line 26, in <module>
    import rpm
  File "/usr/local/lib/python2.7/site-packages/rpm/**init**.py", line 9, in <module>
    from rpm._rpm import *
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/rpm/_rpm.so, 2): Symbol not found: _htonll
  Referenced from: /usr/local/Cellar/rpm4/4.12.0.1/lib/librpm.3.dylib
  Expected in: flat namespace
 in /usr/local/Cellar/rpm4/4.12.0.1/lib/librpm.3.dylib

I'm running on Mac OS X 10.9.4 Python 2.7.5.

**Comment by stepanstipl** [comment] 2015-09-07 12:10
Hi, sorry for delayed response. I was unable to reproduce this one.

It works fine for me (10.10.5, with homebrew python Python 2.7.10) as well as on vanilla OS X Yosemite with system python.

So I would suggest installing homebrew python or upgrading OS X. Then remove and install again this formula.

I'm gonna close this, as don't think I'm able to do anything else about this. Feel free to reopen/comment if you want to follow up. Cheers

**Closed as completed by stepanstipl** 2015-09-07 12:10 UTC
